### PR TITLE
Using Mock MCP 2.1 API (with 0.9 functions) for all of the tests inst…

### PR DESCRIPTION
**Pull request by tonybaloney**
…ead of mock driver classes.

### CODE REVIEW

**Comment by bernard357** [comment]
Thanks Anthony -- difficult manual merge this time, but this is good for my education on GitHub. Next step is to leverage this contribution throughout more tests.

**Comment by bernard357** [comment]
Anthony, there is probably a mismatch in versions of libcloud installed on my computer. After the merge of your pull request, tests fail with the following claim:

`AttributeError: 'DimensionDataMockHttp' object has no attribute '_caas_2_0_8a8f6abc_2745_4d8a_9cbc_8dabe5a7d0e4_infrastructure_datacenter'`

The problem is that this attribute does exist, but with prefix `_caas_2_1`

I have attempted to upgrade plumbery, but receive the following message in feedback: `apache-libcloud 0.19.1-dev is already the active version in easy-install.pth`

Any thought on this issue please? Thanks for your assistance

**Comment by tonybaloney** [comment]
Update to 0.20.0

**Comment by bernard357** [comment]
the simple solution was to read the documentation of libcloud, and to use the pip installer for development version ... thanks
